### PR TITLE
Fix screenshot image

### PR DESCRIPTION
**Pull request by maartenbreddels**
cc @rosteen

This fixes screenshots, which did not include images. Images referred to blob URLs, we transform them to dataUrl's so they are embedded in the svg (and thus also appear in the png)

### CODE REVIEW

**Comment by rosteen** [comment]
After pip installing `bqplot` from this branch the `jdaviz` app that I'm testing fails to load. See screenshot for errors in the dev console (they continue, but appear to all be repetitions of the same error):

Screen Shot 2020-08-18 at 1 41 32 PM

**Comment by maartenbreddels** [comment]
did you do a dev install?

**Comment by maartenbreddels** [comment]
FYI: the reason why I think so is that your bqplot/extension.js does not seem to be loaded, which causes requirejs to fetch static/bqplot.js. 
For dev install you would need to add:
```
# jupyter nbextension install --py --symlink --sys-prefix bqplot
$ jupyter nbextension enable --py --sys-prefix bqplot
```

**Comment by rosteen** [comment]
Ah, you're correct - I totally forgot to run the nbextension commands. Working after I ran those.

**Review by martinRenou — APPROVED** [review]
LGTM :+1:

**Pull request merged**
