### PR TITLE
Visual regression testing

### LINKED ISSUE #1308: Visual regression testing with Galata
We should add visual regression testing with Galata, like in https://github.com/jupyter-widgets/ipywidgets/pull/3172

### PR DESCRIPTION
**Pull request by martinRenou**
Fix #1308

### CODE REVIEW

**Comment by martinRenou** [comment]
@mbektasbbg would you mind giving this a look? I changed a bit the logic in comparison with your PR in ipywidgets. 

I plan on splitting tests into multiple Notebooks, making it easier to maintain.

**Comment by jtpio** [comment]
Nice!

Out of curiosity, was it possible to check it catches regressions, for example like in https://github.com/mbektasbbg/ipywidgets/pull/4 in a fork repo?

**Comment by martinRenou** [comment]
Sure, I'll open a PR that checks that :)

**Comment by martinRenou** [comment]
@jtpio https://github.com/martinRenou/bqplot/pull/2 It looks like it fails as intended :)

**Comment by jtpio** [comment]
Nice, looks great!

**Pull request merged**
