### PR TITLE
MarketMap: Debounce relayout calls

### LINKED ISSUE #1015: MarketMap should debounce relayout calls
We should apply the equivalent patch @maartenbreddels did in https://github.com/bloomberg/bqplot/pull/993, but this time for `MarketMap`.

debounced

### PR DESCRIPTION
**Pull request by martinRenou**
This will fix #1015, it is an update of the MarketMap figure related to #993 and #982

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@martinRenou what is the status of this PR?

**Comment by martinRenou** [comment]
Not sure. I would need to look at it again. I think some more changes happened in the figure in the meantime.

**Comment by SylvainCorlay** [comment]
That would be nice. I am making a pass on the main bugfixes that are pending to make a 0.12.7 release.

**Comment by martinRenou** [comment]
@SylvainCorlay  Rebased

**Pull request merged**
