### PR TITLE
Backport PR #1539: fix: figure is not updating when margins change

### PR DESCRIPTION
**Pull request by mariobuikhuizen**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
@martinRenou what do you think, should we port https://github.com/bqplot/bqplot/pull/1550/files to 0.12.x?

**Comment by martinRenou** [comment]
Yes we should backport some of the recent PRs, I can look into it

**Comment by pllim** [comment]
xref

* https://github.com/spacetelescope/jdaviz/issues/1397
* https://github.com/spacetelescope/jdaviz/issues/1671
* https://github.com/spacetelescope/jdaviz/issues/1987

**Comment by maartenbreddels** [comment]
@mariobuikhuizen needs a prettifier run

@martinRenou maybe we should let the rest of CI run, even if prettifier fails (so it's a sub step), and maybe have pre commit.. ?

**Comment by maartenbreddels** [comment]
awesome!

**Comment by mariobuikhuizen** [comment]
It's this one: spacetelescope/jdaviz#1671.

**Comment by pllim** [comment]
Great, thanks! Can you please let us know when this patch is released and we can then update the bqplot pin downstream? 🙏

**Pull request merged**
