### PR TITLE
EXP: Bump pandas maxversion to v2

### PR DESCRIPTION
**Pull request by pllim**
Bump pandas maxversion to v2 and see how badly things break.

## References

* #1586

## Code changes

See diff.

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by pllim** [comment]
Hmm, nothing is running in the CI. 🤷

**Comment by maartenbreddels** [comment]
Prediction: this doesn't fail, and we should not have pinned. Now we can never test older versions of bqplot with newer versions of pandas

famous last words.. ?

**Comment by pllim** [comment]
Actually, will the existing jobs even pick up pandas pre-release? How do I make it do that?

**Review by martinRenou — APPROVED** [review]
Thanks!

**Comment by martinRenou** [comment]
meeseeksdev please backport to master

**Comment by martinRenou** [comment]
meeseeksdev backport to 0.12.x ?

**Comment by martinRenou** [comment]
meeseeksdev backport to 0.12.x

**Comment by martinRenou** [comment]
https://github.com/bqplot/bqplot/pull/1596

**Pull request merged**
