### PR TITLE
fix: properly treat Bar.base with stacked Bars

### PR DESCRIPTION
**Pull request by maartenbreddels**
This also allows the use of bars with log scales

# bug

We currently subtract `base` (baseValue in js code) each time from the value, which caused stacked bars to not show correct values. See demonstration of the bug:
bqplot-bars-base-bug

Code to reproduce:
```python
import bqplot
import numpy as np
import bqplot.pyplot as plt
N = 1000
np.random.seed(42)
log = False
sx = bqplot.LinearScale(min=0, max=4)
sy = bqplot.LinearScale(min=-2, max=6)
if log:
    sy = bqplot.LogScale(min=0.1, max=10)

fig = plt.figure(scale_x=sx, scale_y=sy)
x, y, c = np.random.normal(size=(3, N))
# mark = plt.scatter(x, y**2)
# h = plt.bar(x, y**2)
if log:
    mark = plt.bar([1,2,3], [[1, 1, 1], [2, 3, 4]], base=0.1, color=["orange", "green"], scales={'x': sx, 'y': sy})
else:
    mark = plt.bar([1,2,3], [[1, -1, 1], [2, -3, 4]], base=0, color=["orange", "green"], scales={'x': sx, 'y': sy})
plt.show()
import ipywidgets as widgets
if log:
    slider = widgets.FloatLogSlider(min=-1, max=1.5, step=0.01)
else:
    slider = widgets.FloatSlider(min=-1, max=7)
    
widgets.jslink((mark, 'base'), (slider, 'value'))
slider
```

# solution

I've refactored the code a bit, which makes it easier to comprehend I think, and corrected the double subtraction.

Bars now behave as I expect:
bqplot-bars-base

There are a few issues/cornercase:
 * If base is larger then the first bar value, there is no proper way to display it, so we skip it and print a warning to the console.
 * Using a log scale, negative bars (i.e. where base is larger then the cumulate sum of y) makes totally no sense, but one could argue that's the user error.

### CODE REVIEW

**Review by martinRenou — COMMENTED** [review]
Should the top of the bars actually be equal to `base + y`?

IIUC, that is what plotly does:
base


This would fix your issue with stacked bars, because bars would always have the same height, whatever the base is.

**Comment by maartenbreddels** [comment]
I think the current behaviour makes sense, given that if you plot in log space, and base is 10, and y value is 100, you want a bar from `10` to `100`, not till `110`

**Comment by ibdafna** [comment]
@maartenbreddels Are you still looking to pursue this? Looks not not based on the last comment, but I thought I'd ask 😃

**Comment by maartenbreddels** [comment]
Yeah, I think this is ready for review/merge. I just expressed I disagreed with Martin. Also, as it is now, the behaviour is the same as before, so non-breaking.

**Comment by maartenbreddels** [comment]
@mariobuikhuizen and I looked at this, we think this is an improvement, replaces #1375 and fixes #1300

Good to merge @martinRenou ?

**Comment by maartenbreddels** [comment]
It fixes a 'subset' of #1300, which is LogScale with non-negative values and a non-negative base (which the user has to set).

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
