### PR TITLE
Refactor BrushSelector

### PR DESCRIPTION
**Pull request by martinRenou**
I looked for having a mixin class to reduce the code duplication in this file, unfortunately it seems impossible at the moment when base classes are abstract https://github.com/microsoft/TypeScript/issues/29653

### CODE REVIEW

**Comment by martinRenou** [comment]
Syncing the views is not implemented in MultiSelector. We should always construct the same number of brushes in each view. Let's do this in another PR.

**Comment by martinRenou** [comment]
This PR fixes multiple issues on the MultiSelector, some similar to https://github.com/bqplot/bqplot/pull/1202.

- Fix filling of the selectors (the MultiSelector used to render the entire draw area in blue since 0.12.0)
- Fix labels rendering
- Fix labels positioning on relayout
- Fix relayout of the MultiSelector
- Code factorizing and cleaning

It also fixes events bouncing in the BrushSelector

**Comment by martinRenou** [comment]
@ibdafna we discussed including this PR in the release during last call. It fixes quite a few problems on the selectors.

**Comment by maartenbreddels** [comment]
Excellent work!

**Comment by martinRenou** [comment]
Thanks!

**Pull request merged**
