### PR TITLE
feat: make a PNG export of the figure available in the kernel

### PR DESCRIPTION
**Pull request by mariobuikhuizen**
A solution for #1393

Usage:
```python
def on_png_received(data):
    with open('mychart.png', 'bw') as f:
        f.write(data)

figure.get_png_data(on_png_received)
```

### CODE REVIEW

**Comment by maartenbreddels** [comment]
LGTM, would like a 2nd opinion from @SylvainCorlay or @martinRenou on this.

Some thoughts that don't need addressing perse:
 * download vs upload depends on your perspective, maybe we can avoid that word, maybe call the event 'send_msg'?
 * This particular use case is asking for a `await fig.get_png_data_async()`, which might work with @davidbrochart 's https://github.com/davidbrochart/akernel

**Comment by martinRenou** [comment]
Rebased

**Comment by pllim** [comment]
Thanks! Nice! Which release will this feature be in? 😸

**Comment by martinRenou** [comment]
0.12.31 :) It should come soon

**Pull request merged**
