### PR TITLE
chore: update ci, backport of #1550

### PR DESCRIPTION
**Pull request by maartenbreddels**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
@martinRenou CI is working for 0.12.x, but not sure why this regression happened. Maybe you have seen this error before?

**Comment by martinRenou** [comment]
It looks like ScatterGL does not work anymore in this branch. I've not seen this happen on master.

**Comment by maartenbreddels** [comment]
For some reason we went from yarn 1 to 3, and that broke a lot, so we're not limiting yarn to <2

**Comment by martinRenou** [comment]
Yeah I see the yarn=1 constraint pop up here and there

**Comment by maartenbreddels** [comment]
@martinRenou can we get the js console output. Looking at the video, we don't get any WebGL output, so it's not a timing issue.

**Comment by maartenbreddels** [comment]
@martinRenou found out how to get js console output, I now see
```
PAGE LOG: THREE.WebGLRenderer 91
PAGE LOG: THREE.WebGLShader: Shader couldn't compile.
PAGE LOG: THREE.WebGLShader: Shader couldn't compile.
PAGE LOG: THREE.WebGLProgram: shader error:  0 gl.VALIDATE_STATUS false gl.getProgramInfoLog   
PAGE LOG: WebGL: INVALID_OPERATION: useProgram: program not valid
PAGE LOG: WebGL: INVALID_OPERATION: drawElementsInstancedANGLE: no valid shader program in use
PAGE LOG: WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
```

So it seems there is a WebGL issue now, any ideas how to reproduce this locally? Or what can cause this? Maybe it's a playwright version issue.

**Comment by maartenbreddels** [comment]
This was really tricky to get green 😫 

The problem was the 22.04 ubuntu image (ubuntu-latest). I thought I already changed that, but I only changed it for 1 step, not the `visual-regression-tests`. Setting `visual-regression-tests` to ubuntu-20.04 solved it.

Still not sure what the problem is, but maybe in a year from now this problem goes away.

**Pull request merged**
