### PR TITLE
Improve bqplot classic theme

### PR DESCRIPTION
**Pull request by SylvainCorlay**
# Bqplot 0.11 had two different skins

A dark theme and a light theme.

The original light theme is similar to ggplot, with a light gray background and white gridlines.

original-light

The original dark theme is a more "classic" wireframe style.

original-dark

# Bqplot 0.12 introduced the coloring based on JupyterLab colors

Since 0.12, bqplot makes use of the JupyterLab CSS variables for the coloring of the plot background to match the environment.

However, we kept two options for the bqplot styling: the "**gg**" style, similar to ggplot, and the "**classic**" style with the wireframe look. Roughly, "gg" looks like the original light theme in the with the JupyterLab light theme, and "classic" looks like the original dark theme in the JupyterLab dark theme

## 0.12 light "gg"

old-gg-light

## 0.12 light "classic"

old-classic-light

## 0.12 dark "gg"

old-gg-dark

## 0.12 dark "classic"

old-classic-dark

# In this PR

In this PR, I rework the colors to be closer to the original, especially in the dark theme. We still use JupyterLab variables.

## New light "gg"

new-gg-light

## New light "classic"

new-classic-light

## New dark "gg"

new-gg-dark

## New dark "classic"

new-classic-dark

I think these changes improve the visual look of the dark theme, especially in the "gg" theme. In the classic mode, the axis lines are more highlighted and grid lines a bit less visible

### CODE REVIEW

**Comment by cquah** [comment]
@kaiayoung for awareness!

**Comment by ChakriCherukuri** [comment]
@SylvainCorlay many thanks for doing this.
The removal of plot background is a huge plus especially when you stack multiple charts using hbox/vbox.

I am proposing a few changes to gridlines and ticks as follows

Current dark (as done in this PR):
current_dark

What I am proposing:
proposed_dark

preferred gridlines stroke: #3b3b3b
preferred tick text fill: #b3b3b3

Please see if you can as close to this from the existing colors you have. Happy to chat further.

**Comment by ChakriCherukuri** [comment]
classic looks good btw.

**Comment by SylvainCorlay** [comment]
New version with dimmer grid lines and axes:

## light "gg"

dim-gg-light

## light "classic"

dim-classic-light

## dark "gg"

dim-gg-dark

## dark "classic"

dim-classic-dark

**Comment by SylvainCorlay** [comment]
@ChakriCherukuri I think this is pretty close to the sceenshot you shared (except for the notebook background which is part of JupyterLab). I will be merging this when all is green.

**Comment by ChakriCherukuri** [comment]
LGTM

**Pull request merged**
