### PR TITLE
Improve setup.py

### PR DESCRIPTION
**Pull request by martinRenou**
- Minor PEP8 issues
- Unused imports
- Change setup call in order to fix the `Used by` button in Github (workaround Github's linguist parsing issue)

### CODE REVIEW

**Comment by martinRenou** [comment]
@maartenbreddels it looks like the `name = "bqplot"` is the key for fixing the linguist issue

**Comment by maartenbreddels** [comment]
Yeah, I was looking at this :) Thanks!

**Comment by martinRenou** [comment]
Would you like me to come up with a PR in ipyvolume? I never contributed to it I think!

**Comment by maartenbreddels** [comment]
Would love that!

**Pull request merged**
