### PR TITLE
fix: display and resize plots when not in a lumino context

### PR DESCRIPTION
**Pull request by mariobuikhuizen**
## References
no issue for this yet

## Code changes
Use a combination of `IntersectionObserver` and `ResizeObserver` instead of lumino-events to control relayouts, so this works when lumino-events are not available. This is the case when embedding bqplot in an ipyvuetify-template.

The typescript version was changed to have type support for ResizeObserver.

## User-facing changes
before:

https://user-images.githubusercontent.com/46192475/194905971-9cd46938-2f32-4f91-8c0d-716abe058276.mp4

after:

https://user-images.githubusercontent.com/46192475/194906020-9d7f377f-3c61-4bfe-9f2e-d05a7d8d33ee.mp4

To reproduce:
```python
pip install ipyvuetify ipygoldenlayout
```

```python
import ipyvuetify as v
import traitlets
from ipygoldenlayout import GoldenLayout
import ipywidgets

import numpy as np
import bqplot.pyplot as plt

size = 100
scale = 100.0
np.random.seed(0)
x_data = np.arange(size)
y_data = np.cumsum(np.random.randn(size) * scale)

GoldenLayout()

def make_plot(name):
    fig = plt.figure(title=name)
    plt.plot(y_data)
    fig.layout.min_height = '100%'
    fig.layout.height = '100%'
    fig.layout.max_height = '100%'
    return fig

figs = [make_plot(f"plot{i}") for i in range(3)]

class MultiPlot(v.VuetifyTemplate):
    
    plot1 = traitlets.Any().tag(sync=True, **ipywidgets.widget_serialization)
    plot2 = traitlets.Any().tag(sync=True, **ipywidgets.widget_serialization)
    plot3 = traitlets.Any().tag(sync=True, **ipywidgets.widget_serialization)

    @traitlets.default("template")
    def _template(self):
        return """
        <template>
            <div >
                <golden-layout style="height: 400px">
                  <gl-row>
                    <gl-component title="component1">
                      <jupyter-widget :widget="plot1"></jupyter-widget>
                    </gl-component>
                    <gl-stack>
                      <gl-component title="component2">
                        <jupyter-widget :widget="plot2"></jupyter-widget>
                      </gl-component>
                      <gl-component title="component3" >
                        <jupyter-widget :widget="plot3"></jupyter-widget>  
                      </gl-component>
                    </gl-stack>
                  </gl-row>
                </golden-layout>
            </div>
        </template>
        """
    
MultiPlot(plot1=figs[0], plot2=figs[1], plot3=figs[2])
```

A similar PR, but without resize support: #1029

### CODE REVIEW

**Comment by maartenbreddels** [comment]
See also https://github.com/jupyter-widgets/ipywidgets/issues/3282

**Comment by maartenbreddels** [comment]
I guess we need to limit yarn, see https://github.com/bqplot/bqplot/pull/1588#issuecomment-1458426230

**Review by martinRenou — APPROVED** [review]
LGTM! Thanks

**Comment by martinRenou** [comment]
meeseeksdev please backport to 0.12.x

**Pull request merged**
