### PR TITLE
Use mamba-org/setup-micromamba for visual job

### PR DESCRIPTION
**Pull request by pllim**
See if this helps.

### CODE REVIEW

**Comment by pllim** [comment]
Well, at least it ran to completion now, but has some real comparison failures that are beyond my skills to fix.

**Comment by maartenbreddels** [comment]
The diff is visually very small, maybe it's a animation issue/fluke.

@martinRenou any idea what can cause this? A jupyter-lab css variable that changed maybe?

**Comment by maartenbreddels** [comment]
update galata references

**Comment by maartenbreddels** [comment]
update galata references

**Comment by maartenbreddels** [comment]
Annoying, I think the update script looks at who opened the PR, not who send the message.

@martinRenou can you confirm that? And is there a reason for this?

**Comment by martinRenou** [comment]
Indeed, that was the proposed fix when a CVE about this was published so I copied it over in all repos.

I think the solution in here is nicer (looking at the message author as you suggest): https://github.com/jupytercad/JupyterCAD/blob/main/.github/workflows/update_galata_references.yaml

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
