### PR TITLE
Log console messages in UI-tests + fix visual regression tests

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
@mariobuikhuizen @maartenbreddels visual regression tests passing again! I think we were facing https://github.com/jupyter-widgets/ipywidgets/pull/3549 and updating the `yarn.lock` did the trick

**Comment by maartenbreddels** [comment]
Great to hear!
What makes you think https://github.com/jupyter-widgets/ipywidgets/pull/3549 was the problem? Note that I found out today this was also present in widgets 7 https://github.com/jupyter-widgets/ipywidgets/pull/3687

**Comment by martinRenou** [comment]
> What makes you think https://github.com/jupyter-widgets/ipywidgets/pull/3549 was the problem?

I'm not entirely sure this was the culprit. But we've seen very similar symptoms in ipyleaflet https://github.com/jupyter-widgets/ipyleaflet/pull/968#issuecomment-1219895024: issue in fetching some sub-widget state and not reproducible outside of Galata. So that's what makes me think it's the reason.

**Comment by mariobuikhuizen** [comment]
Thanks for the notification @martinRenou! I've updated #1539, which now has no visual regression.

**Pull request merged**
